### ISSUE TITLE
Clean install of vips8 and gir_ffi-vips crashes on first Vips call

### ISSUE THREAD

**Issue by PaulHowson** [jcupitt/gir_ffi-vips#1] opened 2015-09-15 06:59 UTC
Have been experiencing ongoing inability to use vips8 with Ruby since upgrading from vips7 and ruby-vips. See reports on this thread:

```
https://github.com/jcupitt/libvips/issues/322
```

So, did a clean install of vips8 and girl_ffi-vips on a second Macbook Pro which recently had clean install of Yosemite — i.e. nothing could be lurking around from old vips installs.

Installed Homebrew, vips (via Homebrew), the gir_ffi-vips gem, and its dependencies, etc, etc.

Ran this little "write black" test file:

``` ruby
require 'vips8'
im = Vips::Image.black(200, 200)
im.write_to_file('test_image.png')
```

Produces this crash on the first vips call (Image.black):

```
type_builder.rb:38: in `builder_for': undefined method `new' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/gir_ffi-0.7.9/lib/gir_ffi/builders/type_builder.rb:33:in `build'
    from /Library/Ruby/Gems/2.0.0/gems/gir_ffi-0.7.9/lib/gir_ffi/builder.rb:14:in `build_class'
    from /Library/Ruby/Gems/2.0.0/gems/gir_ffi-0.7.9/lib/gir_ffi/builders/module_builder.rb:40:in `build_namespaced_class'
```

…rest of the stack trace omitted.

Same thing happens if first call is `Vips::Image.new_from_file`. Reported this on other thread but no response.

This is a deal-stopper for vips and Ruby at present.

Paul

**Comment by jcupitt** [comment] 2015-09-15 08:29
Sorry I've been so poor at responding to this issue Paul. I'm trapped in a JavaScript project at the moment, with an October deadline. It's been three weeks now, weekends included :( I will try to address this.

**Comment by PaulHowson** [comment] 2015-09-16 01:55
Hi John. Good to hear your'e still OK, even if trapped in a Javascript project. :) Will await your response whenever.

**Comment by PaulHowson** [comment] 2015-10-09 07:48
Hi John. How's the Javascript project going? Any idea yet when you might get to look at this apparent git_ffi-vips bug?

**Comment by jcupitt** [comment] 2015-10-10 14:23
Not really done, but done enough for me to mostly give up. I have a feeling this happens a lot with javascript projects. 

I think gir_ffi will probably not get fixed any time soon. I'm changing tack slightly: I did a ruby vips8 binding using the official gnome ruby framework:

https://github.com/jcupitt/ruby-vips8

This has the opposite problem to gir_ffi: they support annotations, but they are missing some constructors. The last time I tried (back in Feb) you couldn't create a boxed object from an array type, and this broke vips8 array constants.

I have a few hours this weekend, I'll try again based on the latest version of their thing. Perhaps they've added the stuff we need.

**Comment by jcupitt** [comment] 2015-10-10 14:42
Looks like they've added init from array constants!

```
$ irb
irb(main):001:0> require 'vips8'
=> true
irb(main):002:0> Vips::ArrayInt.new [1,2,3]
=> #<Vips::ArrayInt:0x000000026edb40 @struct=#<Vips::ArrayInt::Struct:0x000000026edb18>>
```

I'll see if I can fix it up a bit. It's exactly the same API as `gir_ffi-vips8`, just based on a different back end, so it should be an easy switch for you.

**Comment by PaulHowson** [comment] 2015-10-12 06:14
John,

Thanks for those two updates.

Let me see if I've got this correct…

I gather you're saying that the problem noted at the start of this thread — a clean install of vips8 and girl_ffi-vips crashing — is due to an unresolved bug in gir_ffi, which is not likely to get fixed soon.

And you're saying that the other binding you did, github.com/jcupitt/ruby-vips8, had some dealstopper omissions (back in February), but one of these at least appears to have been fixed, so this could be a viable option for vips8 with Ruby.

This is promising.

Looking forward to an eventual solution.

Paul

**Comment by jcupitt** [comment] 2015-10-21 13:42
Hi again Paul, a quick update.

I've fixed up ruby-vips8 a bit and it now mostly works:

https://github.com/jcupitt/ruby-vips8

But I've found a problem in gobject-introspection, the gem ruby-vips8 uses to talk to libvips. I've posted a bug report:

http://sourceforge.net/p/ruby-gnome2/mailman/message/34555949/

Hopefully it'll be fixed soon, kou has been very good on bugs in the past.

In the meantime, I've worked around the problem a bit and it now "only" segvs every 100 - 500 images. You can make it reliable by adding a `GC.start` before every call to vips (to stop the GC triggering during a call, the cause of the crash), but of course this will hurt performance badly.

There are a couple more things to fix in it still, but it's at the point where it could be tried out. 

Thanks for your patience with this :-( it's been a very painful process.

**Comment by jcupitt** [comment] 2015-10-26 10:31
See this issue for more news, I'll close this one for now.

https://github.com/jcupitt/libvips/issues/322

**Closed as completed by jcupitt** 2015-10-26 10:31 UTC
Labels: bug
